---
kind: NgrokTrafficPolicy
apiVersion: ngrok.k8s.ngrok.com/v1alpha1
metadata:
  name: limit-game-reloads
spec:
  policy:
    inbound:
      - name: LimitGameReloads
        actions:
          - type: "rate-limit"
            config:
              name: "Only allow 100 requests per minute"
              algorithm: "sliding_window"
              capacity: 100
              rate: "60s"
              bucket_key:
                - "conn.client_ip"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-2048
  annotations:
    k8s.ngrok.com/traffic-policy: limit-game-reloads
spec:
  ingressClassName: ngrok
  rules:
    - host: 2048-demo.ngrok.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game-2048
                port:
                  number: 80