---
kind: NgrokTrafficPolicy
apiVersion: ngrok.k8s.ngrok.com/v1alpha1
metadata:
  name: deny-querys
spec:
  policy:
    inbound:
      - name: DenyQueryParams
        Expressions:
          - "req.url.query != ''"
        actions:
          - type: "deny"
            config:
              status_code: 422
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-2048
  annotations:
    k8s.ngrok.com/traffic-policy: deny-querys
spec:
  ingressClassName: ngrok
  rules:
    - host: 2048-demo.ngrok.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game-2048
                port:
                  number: 80