---
kind: NgrokTrafficPolicy
apiVersion: ngrok.k8s.ngrok.com/v1alpha1
metadata:
  name: variant-policy
spec:
  policy:
    inbound:
      - name: AllowWinnerVariantOnly
        Expressions:
          - "hasQueryParam('variant')"
          - "!('winner' in getQueryParam('variant'))"
        actions:
          - type: "custom-response"
            config:
              status_code: 422
              content: |
                NOT FOUND: ?${req.url.query} <br/> 
                Only the 'winner' variant is allowed <br/>
                <a href="/">Home</a>
              headers:
                Content-type: text/html
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-2048
  annotations:
    k8s.ngrok.com/traffic-policy: variant-policy
spec:
  ingressClassName: ngrok
  rules:
    - host: 2048-demo.ngrok.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game-2048
                port:
                  number: 80